[package]
name = "bevy_framepace"
version = "0.2.0"
edition = "2021"
resolver = "2"
description = "Frame pacing and frame limiting for Bevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aevyrie/bevy_framepace"
documentation = "https://docs.rs/bevy_framepace"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6", default-features = false, features = [
    "render",
    "bevy_winit",
    "x11",
] }
spin_sleep = "1.0"
ringbuffer = "0.8"

[dev-dependencies]
bevy_mod_picking = "0.5"
